admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5432
  user: hluphlyp
  password: chpocpupoc
  database: blackjack
  driver: postgresql+asyncpg
bot:
  token: 6893332938:AAEvs3DyR1-nL2b_Xzxvgf821oA_CAc1T6k
  num_workers: 3

