"""Alembic has been restarted. Added admin table

Revision ID: 6ac94e13cb98
Revises: 580e23b8d51f
Create Date: 2025-04-23 14:45:24.444703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac94e13cb98'
down_revision: Union[str, None] = '580e23b8d51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
