"""Versions have been cleared. Now we have three entities: player, participant and game_session. Also enum game_session.status and participant.status

Revision ID: f8547b8aa85c
Revises: 
Create Date: 2025-04-18 12:00:18.233449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8547b8aa85c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('sleeping', 'waiting_for_num', 'waiting_for_users', 'polling', name='gamesessionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('num_users', sa.Integer(), nullable=True),
    sa.Column('dealer_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_chat_id'), 'game_sessions', ['chat_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_players_tg_id'), 'players', ['tg_id'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('sleeping', 'active', 'polling', 'assembled', name='playerstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('right_hand', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bet', sa.Integer(), nullable=True),
    sa.CheckConstraint('bet = 0 or bet < 0', name='positivest bet'),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_session_id', 'player_id', name='session_tg_unique')
    )
    op.create_index(op.f('ix_participants_game_session_id'), 'participants', ['game_session_id'], unique=False)
    op.create_index(op.f('ix_participants_player_id'), 'participants', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_player_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_game_session_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_players_tg_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_game_sessions_chat_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
