"""String status fields have no limits

Revision ID: 7e28892dbca8
Revises: 50e68876490d
Create Date: 2025-04-16 18:26:19.929429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e28892dbca8'
down_revision: Union[str, None] = '50e68876490d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_game_session_id'), 'players', ['game_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_game_session_id'), table_name='players')
    # ### end Alembic commands ###
