"""Alembic has been restarted. Added admin table

Revision ID: 6d556ce191f7
Revises: 6ac94e13cb98
Create Date: 2025-04-23 15:32:48.562543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d556ce191f7'
down_revision: Union[str, None] = '6ac94e13cb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
