"""Parameter nullable has been replaced by None in Mapped[|None]. Let's see the effect

Revision ID: 50e68876490d
Revises: 6ffd34b664de
Create Date: 2025-04-14 19:38:09.709136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e68876490d'
down_revision: Union[str, None] = '6ffd34b664de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
