"""The number of tables has been reduced to two. Score and rate fields has been replaced by balance and bet. Hands and cards has been replaced by json field right_hand

Revision ID: 57ef9ed3c83e
Revises: 
Create Date: 2025-04-13 18:02:02.346600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ef9ed3c83e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('num_users', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_chat_id'), 'game_sessions', ['chat_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_session_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('right_hand', sa.JSON(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('bet', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_tg_id'), 'players', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_tg_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_game_sessions_chat_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
