"""Test of enum in one table

Revision ID: e091b9fe4295
Revises: 7e28892dbca8
Create Date: 2025-04-17 21:17:16.197810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e091b9fe4295'
down_revision: Union[str, None] = '7e28892dbca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('game_sessions_id_seq'::regclass)"))
    op.alter_column('game_sessions', 'status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('sleeping', 'waiting_for_num', 'waiting_for_users', 'polling', name='gamesessionstatus', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('game_sessions', 'num_users',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('players', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('players', 'game_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('players', 'right_hand',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('players', 'balance',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('players', 'bet',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_players_tg_id', table_name='players')
    op.create_index(op.f('ix_players_tg_id'), 'players', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_tg_id'), table_name='players')
    op.create_index('ix_players_tg_id', 'players', ['tg_id'], unique=True)
    op.alter_column('players', 'bet',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('players', 'balance',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('players', 'right_hand',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('players', 'game_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('players', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('game_sessions', 'num_users',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('game_sessions', 'status',
               existing_type=sa.Enum('sleeping', 'waiting_for_num', 'waiting_for_users', 'polling', name='gamesessionstatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('game_sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('game_sessions_id_seq'::regclass)"))
    # ### end Alembic commands ###
