"""Constraint for unique combinations of players.tg_id and players.game_session_id has been added

Revision ID: 6ffd34b664de
Revises: 57ef9ed3c83e
Create Date: 2025-04-13 18:40:49.874912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffd34b664de'
down_revision: Union[str, None] = '57ef9ed3c83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('session_tg_unique', 'players', ['game_session_id', 'tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_tg_unique', 'players', type_='unique')
    # ### end Alembic commands ###
