"""Waiting for appearing of tables

Revision ID: 390ac2d90415
Revises: 6b72ccb2667d
Create Date: 2025-04-12 14:54:08.628192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390ac2d90415'
down_revision: Union[str, None] = '6b72ccb2667d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
