"""Waiting for appearing of tables

Revision ID: 6b72ccb2667d
Revises: e3afb3f53cac
Create Date: 2025-04-12 14:51:59.660561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b72ccb2667d'
down_revision: Union[str, None] = 'e3afb3f53cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
