"""Waiting for appearing of tables

Revision ID: 79c1c6f19484
Revises: ac2c45e7ba59
Create Date: 2025-04-12 15:04:55.985891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c1c6f19484'
down_revision: Union[str, None] = 'ac2c45e7ba59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('suit', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('num_users', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_chat_id'), 'game_sessions', ['chat_id'], unique=True)
    op.create_table('hands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_tg_id'), 'players', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_tg_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('hands')
    op.drop_index(op.f('ix_game_sessions_chat_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('cards')
    # ### end Alembic commands ###
