"""Waiting for appearing of tables

Revision ID: 86781f981dcf
Revises: 79c1c6f19484
Create Date: 2025-04-12 15:10:08.769994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86781f981dcf'
down_revision: Union[str, None] = '79c1c6f19484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('hand_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'cards', 'hands', ['hand_id'], ['id'], ondelete='CASCADE')
    op.add_column('hands', sa.Column('player_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'hands', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hands', type_='foreignkey')
    op.drop_column('hands', 'player_id')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'hand_id')
    # ### end Alembic commands ###
