"""Yes. we have relations in erd

Revision ID: 8f593dcf88f8
Revises: cab1ffd9e260
Create Date: 2025-04-12 15:12:20.695972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f593dcf88f8'
down_revision: Union[str, None] = 'cab1ffd9e260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('game_session_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'players', 'game_sessions', ['game_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'game_session_id')
    # ### end Alembic commands ###
