"""Waiting for appearing of tables

Revision ID: ac2c45e7ba59
Revises: 390ac2d90415
Create Date: 2025-04-12 14:54:42.545504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2c45e7ba59'
down_revision: Union[str, None] = '390ac2d90415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
